# Generated by Django 2.1.5 on 2019-01-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specuser',
            name='user_type',
            field=models.CharField(choices=[('seller', 'seller'), ('user', 'user'), ('clinic', 'clinic'), ('hospital', 'hospital'), ('bloodbank', 'bloodbank'), ('diagnostic', 'diagnostic')], default='user', max_length=10),
        ),
    ]
